import Link from "next/link";

import { Layout } from "antd";

import HeaderComp from "../../components/HeaderComp";

import websiteLogo from "../app/assets/images/logo.svg";

import 'antd/dist/reset.css';
import "../../styles/reset.css";

export const metadata = {
  title: "Elementor",
  description: "Generated by create next app",
};

const menuItems = [
  { key: 'home', label: <Link href="/">Home</Link> },
  { key: 'about', label: <Link href="/about">About</Link> },
  { key: 'features', label: <Link href="/features">Features</Link> },
  { key: 'contact', label: <Link href="/contact">Contact</Link> },
  {
      key: 'submenu',
      label: 'Pages',
      children: [
        { key: 'detailFeatures', label: <Link href="/detailFeatures">Detail Features</Link> },
        { key: 'teams', label: <Link href="/teams">Teams</Link> },
        { key: 'careers', label: <Link href="/careers">Careers</Link> },
        { key: 'joindoctors', label: <Link href="/joindoctors">Join the Doctors</Link> },
        { key: 'blogs', label: <Link href="/blogs">Blogs</Link> },
        { key: 'singlepost', label: <Link href="/singlepost">Single Post</Link> },
      ],
    },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <RootPage 
          children={children}
        /> */}
            <Layout style={{backgroundColor: "white"}}>
                <HeaderComp
                  websiteLogo={websiteLogo}
                  menuItems={menuItems}
                ></HeaderComp>
                 <div>{children}Content</div>
                <div>Footer</div> 
            </Layout>
      </body>
    </html>
  );
}
