import RootPage from "./page";

export const metadata = {
  title: "Elementor",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <RootPage/>
      </body>
    </html>
  );
}
