import { Layout } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AppLayout from "./AppLayout";
import "../../styles/reset.css";

export const metadata = {
  title: "Elementor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <AppLayout>
            {children}
          </AppLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
